### ISSUE TITLE
MCTS: Implement PUCT

### ISSUE THREAD

**Issue by poja** [poja/RL#10]

**Comment by barakugav** [comment]
09ff16871467a0140196906121d0b8413f0c9c2e

**Comment by barakugav** [comment]
Implemented, should we close this?
Not sure we must compare

**Comment by barakugav** [comment]
see https://docs.google.com/document/d/1QFNRRoPtywh1sWIAnhjxpQQmwHu7MICuaK1KHbNEvao exact MCTS selection calculation

**Comment by barakugav** [comment]
implemented correctly
