### ISSUE TITLE
Play MCTS with network instead of full game simulation

### ISSUE THREAD

**Issue by poja** [poja/RL#18]

**Comment by barakugav** [comment]
Added abstraction in MCTS d56be69f28151a49edc2cc0f6219c7b00ca40aeb
hex/network/simple.rs might be usefull regardless of the model structure, as long as the input/output has the same dimensions. Need to create ValueFunction implementation that uses the network and see what such implementation should save as member values to avoid parsing the model each time

**Comment by barakugav** [comment]
d5453d2702a854a5287dec3bf2a10b8a97e615d7
