### ISSUE TITLE
Implement tic-tac-toe as an example game and train to perfection

### ISSUE THREAD

**Issue by poja** [poja/RL#34]

**Comment by poja** [comment]
Branch tic-tac-toe

**Comment by barakugav** [comment]
https://github.com/poja/RL/pull/38

**Comment by poja** [comment]
Commit hash `9186cdf6` - train with TTT instead of hex. 
I still have a lot to organize and I didn't check if the players are good...

**Comment by poja** [comment]
I think this can be closed, unless we want a more convincing metric of the learning process? 
If we want to be very thorough about it we can try training the policy network to get close to accuracy=1
But I think we can continue to Hex already

**Comment by barakugav** [comment]
agree
