### ISSUE TITLE
Remove "model_id"

### ISSUE THREAD

**Issue by poja** [poja/RL#39]
@barakugav 
It's not so important - I'm just (ab)using this "Issues" platform to discuss something in the code:

What's the goal of the `model_id` function? Can I remove it and just name the directories with the self-play data according to the time they were created? Or if we want to label them by the model that is used, can we use the date of the model creation as its "id"? Why make this complicated hash function?

**Comment by barakugav** [comment]
no need for the complicated hash function, just need a way to have a unique identifier.
time is not a perfect option, as two models can be created at the same time.
when we write a model to a dir, we can name the dir with a random identifier, and that could be it

**Comment by barakugav** [comment]
38fe2310c032205c19cc11164d33068eb825dcd4
